<x-layout title="Edit Mata Kuliah · Kampuskin">
    <section class="page-heading"><div><span class="eyebrow">Pengaturan kelas</span><h1>Edit {{ $course->name }}</h1><p class="subtitle">Perbarui detail dan pengampu mata kuliah.</p></div></section>
    <section class="panel"><form action="{{ route('admin.courses.update', $course) }}" method="POST">@csrf @method('PUT')
        <div class="form-grid">
            <div class="field"><label for="code">Kode mata kuliah</label><input id="code" name="code" value="{{ old('code', $course->code) }}" required>@error('code')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="name">Nama mata kuliah</label><input id="name" name="name" value="{{ old('name', $course->name) }}" required>@error('name')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div class="field span-all"><label for="description">Deskripsi</label><textarea id="description" name="description">{{ old('description', $course->description) }}</textarea>@error('description')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="sks">Jumlah SKS</label><input id="sks" type="number" name="sks" min="1" max="20" value="{{ old('sks', $course->sks) }}" required>@error('sks')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="lecturer_id">Dosen pengampu</label><select id="lecturer_id" name="lecturer_id" required>@foreach ($lecturers as $lecturer)<option value="{{ $lecturer->id }}" @selected(old('lecturer_id', $course->lecturer_id) == $lecturer->id)>{{ $lecturer->name }}</option>@endforeach</select>@error('lecturer_id')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="status">Status kelas</label><select id="status" name="status"><option value="draft" @selected(old('status', $course->status) === 'draft')>Draft</option><option value="active" @selected(old('status', $course->status) === 'active')>Aktif</option><option value="archived" @selected(old('status', $course->status) === 'archived')>Arsip</option></select>@error('status')<p class="field-error">{{ $message }}</p>@enderror</div>
        </div><div class="actions"><button class="btn btn-pink" type="submit">Simpan perubahan</button><a class="btn btn-quiet" href="{{ route('courses.show', $course) }}">Batal</a></div>
    </form></section>
</x-layout>